spring:
  thymeleaf.cache: false
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:postgresql://localhost:5433/booking
    username: postgres
    password: GhjdthrfCt,z
jwt.secret: secret